spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:}
    username: ${SPRING_DATASOURCE_USERNAME:}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:}

  jpa:
    database: mysql
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:}
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: "health"

oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID:}
    client-secret: ${KAKAO_CLIENT_SECRET:}
    redirect-uri: ${KAKAO_REDIRECT_URI:}

jwt:
  secret: ${JWT_SECRET:}
  access-token-validity-seconds: ${JWT_ACCESS_TOKEN_VALIDITY_SECONDS:3600}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:*}
