spring:
  config:
    import:
      - optional:file:.env[.properties]
  datasource:
    url: ${SPRING_DATASOURCE_URL:}
    username: ${SPRING_DATASOURCE_USERNAME:}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  jpa:
    database: mysql
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:}
    open-in-view: false
  data:
    redis:
      host: ${REDIS_HOST:}
      password: ${REDIS_PASSWORD:}

management:
  server:
    base-path: /actuator
  endpoints:
    web:
      exposure:
        include: prometheus, health, metrics
  metrics:
    tags:
      application: ${APP_NAME}
      env: ${SPRING_PROFILES_ACTIVE}

    distribution:
      percentiles-histogram:
        http.server.requests: true
        dependency.timer: true
      percentiles:
        http.server.requests: 0.9, 0.95, 0.99

oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID:}
    client-secret: ${KAKAO_CLIENT_SECRET:}
    redirect-uri: ${KAKAO_REDIRECT_URI:}
    admin-key: ${KAKAO_ADMIN_KEY:}

jwt:
  secret: ${JWT_SECRET:}
  access-token-validity-seconds: ${JWT_ACCESS_TOKEN_VALIDITY_SECONDS:1800}
  refresh-token-validity-seconds: ${JWT_REFRESH_TOKEN_VALIDITY_SECONDS:1209600}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:}

cookie:
  secure: ${COOKIE_SECURE:true}
  same-site: ${COOKIE_SAME_SITE:None}

aws:
  s3:
    bucket: ${AWS_S3_BUCKET:}
    region: ${AWS_REGION:}
    presigned-url-expiration-seconds: ${AWS_S3_PRESIGNED_URL_EXPIRATION_SECONDS:300}
    env-prefix: ${SPRING_PROFILES_ACTIVE}
